services:
  gisportal:
    container_name: gisportal
    platform: linux/amd64
    build: .
    ports:
      - "80:6789"
      - "9229:9229"
    volumes:
      - ./config:/var/portal/GISportal/config
